{
 "title": "model_stats0",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model",
    "query": "select model_name from requests"
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "models",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT \n  model_name, \n  count(*) response_counts \nfrom requests\ngroup by model_name\n    ",
     "rawQueryText": "SELECT \n  model_name, \n  count(*) response_counts \nfrom requests\ngroup by model_name\n    ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Model feedback",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT \n    feedback, \n    COUNT(*) AS count\nFROM \n    feedback\nGROUP BY \n    feedback;",
     "rawQueryText": "SELECT \n    feedback, \n    COUNT(*) AS count\nFROM \n    feedback\nGROUP BY \n    feedback;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT query, response, model_name from requests\n    ",
     "rawQueryText": "SELECT query, response, model_name from requests\n    ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "prompt length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT \nUNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\navg(prompt_length)\nFROM performance_metrics\ngroup by time\norder by time\n",
     "rawQueryText": "SELECT \nUNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\navg(prompt_length)\nFROM performance_metrics\ngroup by time\norder by time\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "response length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT\n  UNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\n  avg(eval_count)\nFROM performance_metrics\nGroup by time\n",
     "rawQueryText": "SELECT\n  UNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\n  avg(eval_count)\nFROM performance_metrics\nGroup by time\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "SELECT \n  UNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\n  avg(total_duration), \n  avg(load_duration), \n  avg(prompt_eval_duration), \n  avg(eval_duration)\nFROM performance_metrics\ngroup by time\norder by time asc\n",
     "rawQueryText": "SELECT \n  UNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\n  avg(total_duration), \n  avg(load_duration), \n  avg(prompt_eval_duration), \n  avg(eval_duration)\nFROM performance_metrics\ngroup by time\norder by time asc\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT \n  UNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\n  model_name,\n  COUNT(*) AS count\nFROM requests \nGROUP BY time, model_name\nORDER BY time, model_name;",
     "rawQueryText": "SELECT \n  UNIXEPOCH(strftime('%Y-%m-%d %H:%M:00', created_at)) AS time,\n  model_name,\n  COUNT(*) AS count\nFROM requests \nGROUP BY time, model_name\nORDER BY time, model_name;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "queryText": "SELECT performance_metrics.*, requests.*\nFROM performance_metrics\nJOIN requests ON performance_metrics.request_id = requests.id;\n",
     "rawQueryText": "SELECT performance_metrics.*, requests.*\nFROM performance_metrics\nJOIN requests ON performance_metrics.request_id = requests.id;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}