version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource  # Correct plugin name
    volumes:
      - grafana-data:/var/lib/grafana  # Persist Grafana data    
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ../app/data/:/app/data  # Volume for SQLite DB file
    ports:
      - "3000:3000"  # Map Grafana port to host
    restart: unless-stopped

volumes:
  grafana-data:

networks:
  elk:
    driver: bridge